apiVersion: v1
kind: Service
metadata:
  name: okon-service
  labels:
    name: okon
spec:
  selector:
    app: okon
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
