apiVersion: apps/v1
kind: Deployment
metadata:
  name: okon-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okon
  template:
    metadata:
      labels:
        app: okon
    spec:
      containers:
      - name: okon
        image: git-registry.gibb.ch/sch140456/dockermodul/okon-website:v1
        ports:
        - containerPort: 80
